version: '3.8'
services:
  db_dev:
    image: postgres:alpine
    container_name: postgres_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: app
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
  db_prod:
    image: postgres:alpine
    container_name: postgres_prod
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: d80F.p<pK>s7:0_`G{[MaOpoXa/R,o-M7pn}8#,JiunYQnDM(
      POSTGRES_PASSWORD: r43V.(aTxM$&Fx£33REl+=^t/E~@MaxI358/24*gGW0?vX
      POSTGRES_DB: app
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
volumes:
  postgres_data_dev:
  postgres_data_prod:
